repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        args:
          - --fix
          - --exit-non-zero-on-fix
      - id: ruff-format
  - repo: local
    hooks:
      - id: enforce-kwargs-spacing
        name: Enforce spaces around keyword equals
        entry: scripts/enforce_kwargs_spacing.py
        language: system
        types: [python]
